---
title: "Stat627 Weekly Notes"
author: "Brian S Yandell"
date: "September 18, 2015"
output: html_document
---

Statistics 627: Professional Skills in Data Science  
Fall 2015 (2 cr)  

### Weekly Notes

#### Notes for Week 1

* intros
* format
* homework -- several based largely on Jenny Bryan’s material
  + see [Jenny Bryan’s homework rubric](http://stat545-ubc.github.io/peer-review01_marking-rubric.html)
* project (for 2nd credit): larger task and possible presentation; info to come
  + can be done in groups
  + need to have individual reports as part of whole
* installing R and Rstudio, and maybe some packages
* lectures: mix of Bates (mostly) & Yandell
* using [JB Stat 545 material](http://stat545-ubc.github.io/)
* expect students to read and follow related material

#### Notes for Week 2

* Bates with laptop but no internet
* went over [Intro.Rmd](https://github.com/dmbates/stat692/blob/master/Intro.Rmd) and [Data.Rmd](https://github.com/dmbates/stat692/blob/master/Data.Rmd)
* discussed ideas on Rmarkdown and data structures
* go through [JB "Deep Thought" slides for cm002](http://stat545-ubc.github.io/cm002_r-rstudio-intro.html) on your own

#### Notes for Week 3

* [gapminder.org](http://gapminder.org): [Hans Rosling TED Talk](http://www.gapminder.org/videos/ted-us-state-department/) & [GapMinder World](http://www.gapminder.org/world)
* Yandell gapminder example
  + ggplot2 basics & git via Rstudio
* Yandell Stat627 example
  + git version control via Rstudio & GitHub
* once per machine:
  + _git config --global user.name 'Brian Yandell'_
  + _git config --global user.email 'byandell@wisc.edu'_
* once per clone (should by automatic within Rstudio using Git Repository)
  + _git remote add origin https://github.com/datascience-uwmadison/stat627_
  + _git push -u origin master_
* add Stat627b -- 2 clones on same origin
* [Test connection between Rstudio & GitHub](http://stat545-ubc.github.io/git00_index.html)
* navigate web page http://www.stat.wisc.edu/network-skills
* if time, [JB’s R Graphics Landscape](http://stat545-ubc.github.io/cm005_still-data-ggplot2-rmarkdown.html)